<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
    http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>orangehrm</groupId>
    <artifactId>orangehrm_framework</artifactId>
    <version>1.0-SNAPSHOT</version>


    <!-- ========================================= -->
    <!-- PROJECT PROPERTIES -->
    <!-- ========================================= -->

    <properties>

        <!-- Java -->
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <project.build.sourceEncoding>
            UTF-8
        </project.build.sourceEncoding>


        <!--
            Default TestNG XML suite.

            Can be overridden from command line:

            mvn clean test -DsuiteXmlFile=admin_suite.xml
        -->
        <suiteXmlFile>
            admin_suite.xml
        </suiteXmlFile>

    </properties>


    <!-- ========================================= -->
    <!-- DEPENDENCIES -->
    <!-- ========================================= -->

    <dependencies>


        <!-- Selenium -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.47.0</version>
        </dependency>


        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.12.0</version>
        </dependency>


        <!-- Apache POI -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.5.1</version>
        </dependency>


        <!-- Apache POI OOXML -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.5.1</version>
        </dependency>


        <!-- Extent Reports -->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>5.1.2</version>
        </dependency>


        <!-- Allure TestNG -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>3.0.0</version>
        </dependency>

    </dependencies>


    <!-- ========================================= -->
    <!-- BUILD -->
    <!-- ========================================= -->

    <build>

        <plugins>


            <!-- ================================= -->
            <!-- MAVEN SUREFIRE / TESTNG -->
            <!-- ================================= -->

            <plugin>

                <groupId>
                    org.apache.maven.plugins
                </groupId>

                <artifactId>
                    maven-surefire-plugin
                </artifactId>

                <version>
                    3.5.4
                </version>


                <configuration>


                    <!--
                        =====================================
                        DYNAMIC TESTNG XML SUITE
                        =====================================

                        All XML suites are stored under:

                        src/test/resources/testng_xml_files/

                        Example:

                        mvn clean test
                        
                        OR

                        mvn clean test
                        -DsuiteXmlFile=admin_suite.xml
                    -->

                    <suiteXmlFiles>

                        <suiteXmlFile>
                            ${project.basedir}/src/test/resources/testng_xml_files/${suiteXmlFile}
                        </suiteXmlFile>

                    </suiteXmlFiles>


                    <!-- ================================= -->
                    <!-- SYSTEM PROPERTIES -->
                    <!-- ================================= -->

                    <systemPropertyVariables>


                        <!-- Allure Results Directory -->

                        <allure.results.directory>
                            ${project.build.directory}/allure-report/allure-results
                        </allure.results.directory>


                    </systemPropertyVariables>


                </configuration>

            </plugin>

        </plugins>

    </build>

</project>